// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ProtocolAppliedWaveletDelta;
@class ProtocolAppliedWaveletDelta_Builder;
@class ProtocolDocumentOperation;
@class ProtocolDocumentOperation_Builder;
@class ProtocolDocumentOperation_Component;
@class ProtocolDocumentOperation_Component_AnnotationBoundary;
@class ProtocolDocumentOperation_Component_AnnotationBoundary_Builder;
@class ProtocolDocumentOperation_Component_Builder;
@class ProtocolDocumentOperation_Component_ElementStart;
@class ProtocolDocumentOperation_Component_ElementStart_Builder;
@class ProtocolDocumentOperation_Component_KeyValuePair;
@class ProtocolDocumentOperation_Component_KeyValuePair_Builder;
@class ProtocolDocumentOperation_Component_KeyValueUpdate;
@class ProtocolDocumentOperation_Component_KeyValueUpdate_Builder;
@class ProtocolDocumentOperation_Component_ReplaceAttributes;
@class ProtocolDocumentOperation_Component_ReplaceAttributes_Builder;
@class ProtocolDocumentOperation_Component_UpdateAttributes;
@class ProtocolDocumentOperation_Component_UpdateAttributes_Builder;
@class ProtocolHashedVersion;
@class ProtocolHashedVersion_Builder;
@class ProtocolSignature;
@class ProtocolSignature_Builder;
@class ProtocolSignedDelta;
@class ProtocolSignedDelta_Builder;
@class ProtocolSignerInfo;
@class ProtocolSignerInfo_Builder;
@class ProtocolWaveletDelta;
@class ProtocolWaveletDelta_Builder;
@class ProtocolWaveletOperation;
@class ProtocolWaveletOperation_Builder;
@class ProtocolWaveletOperation_MutateDocument;
@class ProtocolWaveletOperation_MutateDocument_Builder;
typedef enum {
  ProtocolSignature_SignatureAlgorithmSha1Rsa = 1,
} ProtocolSignature_SignatureAlgorithm;

BOOL ProtocolSignature_SignatureAlgorithmIsValidValue(ProtocolSignature_SignatureAlgorithm value);

typedef enum {
  ProtocolSignerInfo_HashAlgorithmSha256 = 1,
  ProtocolSignerInfo_HashAlgorithmSha512 = 2,
} ProtocolSignerInfo_HashAlgorithm;

BOOL ProtocolSignerInfo_HashAlgorithmIsValidValue(ProtocolSignerInfo_HashAlgorithm value);


@interface CommonRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ProtocolWaveletDelta : PBGeneratedMessage {
@private
  BOOL hasAuthor_:1;
  BOOL hasHashedVersion_:1;
  NSString* author;
  ProtocolHashedVersion* hashedVersion;
  NSMutableArray* mutableAddressPathList;
  NSMutableArray* mutableOperationList;
}
- (BOOL) hasHashedVersion;
- (BOOL) hasAuthor;
@property (readonly, retain) ProtocolHashedVersion* hashedVersion;
@property (readonly, retain) NSString* author;
- (NSArray*) operationList;
- (ProtocolWaveletOperation*) operationAtIndex:(int32_t) index;
- (NSArray*) addressPathList;
- (NSString*) addressPathAtIndex:(int32_t) index;

+ (ProtocolWaveletDelta*) defaultInstance;
- (ProtocolWaveletDelta*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolWaveletDelta_Builder*) builder;
+ (ProtocolWaveletDelta_Builder*) builder;
+ (ProtocolWaveletDelta_Builder*) builderWithPrototype:(ProtocolWaveletDelta*) prototype;

+ (ProtocolWaveletDelta*) parseFromData:(NSData*) data;
+ (ProtocolWaveletDelta*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolWaveletDelta*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolWaveletDelta*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolWaveletDelta*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolWaveletDelta*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolWaveletDelta_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolWaveletDelta* result;
}

- (ProtocolWaveletDelta*) defaultInstance;

- (ProtocolWaveletDelta_Builder*) clear;
- (ProtocolWaveletDelta_Builder*) clone;

- (ProtocolWaveletDelta*) build;
- (ProtocolWaveletDelta*) buildPartial;

- (ProtocolWaveletDelta_Builder*) mergeFrom:(ProtocolWaveletDelta*) other;
- (ProtocolWaveletDelta_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolWaveletDelta_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHashedVersion;
- (ProtocolHashedVersion*) hashedVersion;
- (ProtocolWaveletDelta_Builder*) setHashedVersion:(ProtocolHashedVersion*) value;
- (ProtocolWaveletDelta_Builder*) setHashedVersionBuilder:(ProtocolHashedVersion_Builder*) builderForValue;
- (ProtocolWaveletDelta_Builder*) mergeHashedVersion:(ProtocolHashedVersion*) value;
- (ProtocolWaveletDelta_Builder*) clearHashedVersion;

- (BOOL) hasAuthor;
- (NSString*) author;
- (ProtocolWaveletDelta_Builder*) setAuthor:(NSString*) value;
- (ProtocolWaveletDelta_Builder*) clearAuthor;

- (NSArray*) operationList;
- (ProtocolWaveletOperation*) operationAtIndex:(int32_t) index;
- (ProtocolWaveletDelta_Builder*) replaceOperationAtIndex:(int32_t) index with:(ProtocolWaveletOperation*) value;
- (ProtocolWaveletDelta_Builder*) addOperation:(ProtocolWaveletOperation*) value;
- (ProtocolWaveletDelta_Builder*) addAllOperation:(NSArray*) values;
- (ProtocolWaveletDelta_Builder*) clearOperationList;

- (NSArray*) addressPathList;
- (NSString*) addressPathAtIndex:(int32_t) index;
- (ProtocolWaveletDelta_Builder*) replaceAddressPathAtIndex:(int32_t) index with:(NSString*) value;
- (ProtocolWaveletDelta_Builder*) addAddressPath:(NSString*) value;
- (ProtocolWaveletDelta_Builder*) addAllAddressPath:(NSArray*) values;
- (ProtocolWaveletDelta_Builder*) clearAddressPathList;
@end

@interface ProtocolHashedVersion : PBGeneratedMessage {
@private
  BOOL hasVersion_:1;
  BOOL hasHistoryHash_:1;
  int64_t version;
  NSData* historyHash;
}
- (BOOL) hasVersion;
- (BOOL) hasHistoryHash;
@property (readonly) int64_t version;
@property (readonly, retain) NSData* historyHash;

+ (ProtocolHashedVersion*) defaultInstance;
- (ProtocolHashedVersion*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolHashedVersion_Builder*) builder;
+ (ProtocolHashedVersion_Builder*) builder;
+ (ProtocolHashedVersion_Builder*) builderWithPrototype:(ProtocolHashedVersion*) prototype;

+ (ProtocolHashedVersion*) parseFromData:(NSData*) data;
+ (ProtocolHashedVersion*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolHashedVersion*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolHashedVersion*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolHashedVersion*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolHashedVersion*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolHashedVersion_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolHashedVersion* result;
}

- (ProtocolHashedVersion*) defaultInstance;

- (ProtocolHashedVersion_Builder*) clear;
- (ProtocolHashedVersion_Builder*) clone;

- (ProtocolHashedVersion*) build;
- (ProtocolHashedVersion*) buildPartial;

- (ProtocolHashedVersion_Builder*) mergeFrom:(ProtocolHashedVersion*) other;
- (ProtocolHashedVersion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolHashedVersion_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasVersion;
- (int64_t) version;
- (ProtocolHashedVersion_Builder*) setVersion:(int64_t) value;
- (ProtocolHashedVersion_Builder*) clearVersion;

- (BOOL) hasHistoryHash;
- (NSData*) historyHash;
- (ProtocolHashedVersion_Builder*) setHistoryHash:(NSData*) value;
- (ProtocolHashedVersion_Builder*) clearHistoryHash;
@end

@interface ProtocolWaveletOperation : PBGeneratedMessage {
@private
  BOOL hasNoOp_:1;
  BOOL hasAddParticipant_:1;
  BOOL hasRemoveParticipant_:1;
  BOOL hasMutateDocument_:1;
  BOOL noOp_:1;
  NSString* addParticipant;
  NSString* removeParticipant;
  ProtocolWaveletOperation_MutateDocument* mutateDocument;
}
- (BOOL) hasAddParticipant;
- (BOOL) hasRemoveParticipant;
- (BOOL) hasMutateDocument;
- (BOOL) hasNoOp;
@property (readonly, retain) NSString* addParticipant;
@property (readonly, retain) NSString* removeParticipant;
@property (readonly, retain) ProtocolWaveletOperation_MutateDocument* mutateDocument;
- (BOOL) noOp;

+ (ProtocolWaveletOperation*) defaultInstance;
- (ProtocolWaveletOperation*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolWaveletOperation_Builder*) builder;
+ (ProtocolWaveletOperation_Builder*) builder;
+ (ProtocolWaveletOperation_Builder*) builderWithPrototype:(ProtocolWaveletOperation*) prototype;

+ (ProtocolWaveletOperation*) parseFromData:(NSData*) data;
+ (ProtocolWaveletOperation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolWaveletOperation*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolWaveletOperation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolWaveletOperation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolWaveletOperation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolWaveletOperation_MutateDocument : PBGeneratedMessage {
@private
  BOOL hasDocumentId_:1;
  BOOL hasDocumentOperation_:1;
  NSString* documentId;
  ProtocolDocumentOperation* documentOperation;
}
- (BOOL) hasDocumentId;
- (BOOL) hasDocumentOperation;
@property (readonly, retain) NSString* documentId;
@property (readonly, retain) ProtocolDocumentOperation* documentOperation;

+ (ProtocolWaveletOperation_MutateDocument*) defaultInstance;
- (ProtocolWaveletOperation_MutateDocument*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolWaveletOperation_MutateDocument_Builder*) builder;
+ (ProtocolWaveletOperation_MutateDocument_Builder*) builder;
+ (ProtocolWaveletOperation_MutateDocument_Builder*) builderWithPrototype:(ProtocolWaveletOperation_MutateDocument*) prototype;

+ (ProtocolWaveletOperation_MutateDocument*) parseFromData:(NSData*) data;
+ (ProtocolWaveletOperation_MutateDocument*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolWaveletOperation_MutateDocument*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolWaveletOperation_MutateDocument*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolWaveletOperation_MutateDocument*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolWaveletOperation_MutateDocument*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolWaveletOperation_MutateDocument_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolWaveletOperation_MutateDocument* result;
}

- (ProtocolWaveletOperation_MutateDocument*) defaultInstance;

- (ProtocolWaveletOperation_MutateDocument_Builder*) clear;
- (ProtocolWaveletOperation_MutateDocument_Builder*) clone;

- (ProtocolWaveletOperation_MutateDocument*) build;
- (ProtocolWaveletOperation_MutateDocument*) buildPartial;

- (ProtocolWaveletOperation_MutateDocument_Builder*) mergeFrom:(ProtocolWaveletOperation_MutateDocument*) other;
- (ProtocolWaveletOperation_MutateDocument_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolWaveletOperation_MutateDocument_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDocumentId;
- (NSString*) documentId;
- (ProtocolWaveletOperation_MutateDocument_Builder*) setDocumentId:(NSString*) value;
- (ProtocolWaveletOperation_MutateDocument_Builder*) clearDocumentId;

- (BOOL) hasDocumentOperation;
- (ProtocolDocumentOperation*) documentOperation;
- (ProtocolWaveletOperation_MutateDocument_Builder*) setDocumentOperation:(ProtocolDocumentOperation*) value;
- (ProtocolWaveletOperation_MutateDocument_Builder*) setDocumentOperationBuilder:(ProtocolDocumentOperation_Builder*) builderForValue;
- (ProtocolWaveletOperation_MutateDocument_Builder*) mergeDocumentOperation:(ProtocolDocumentOperation*) value;
- (ProtocolWaveletOperation_MutateDocument_Builder*) clearDocumentOperation;
@end

@interface ProtocolWaveletOperation_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolWaveletOperation* result;
}

- (ProtocolWaveletOperation*) defaultInstance;

- (ProtocolWaveletOperation_Builder*) clear;
- (ProtocolWaveletOperation_Builder*) clone;

- (ProtocolWaveletOperation*) build;
- (ProtocolWaveletOperation*) buildPartial;

- (ProtocolWaveletOperation_Builder*) mergeFrom:(ProtocolWaveletOperation*) other;
- (ProtocolWaveletOperation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolWaveletOperation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAddParticipant;
- (NSString*) addParticipant;
- (ProtocolWaveletOperation_Builder*) setAddParticipant:(NSString*) value;
- (ProtocolWaveletOperation_Builder*) clearAddParticipant;

- (BOOL) hasRemoveParticipant;
- (NSString*) removeParticipant;
- (ProtocolWaveletOperation_Builder*) setRemoveParticipant:(NSString*) value;
- (ProtocolWaveletOperation_Builder*) clearRemoveParticipant;

- (BOOL) hasMutateDocument;
- (ProtocolWaveletOperation_MutateDocument*) mutateDocument;
- (ProtocolWaveletOperation_Builder*) setMutateDocument:(ProtocolWaveletOperation_MutateDocument*) value;
- (ProtocolWaveletOperation_Builder*) setMutateDocumentBuilder:(ProtocolWaveletOperation_MutateDocument_Builder*) builderForValue;
- (ProtocolWaveletOperation_Builder*) mergeMutateDocument:(ProtocolWaveletOperation_MutateDocument*) value;
- (ProtocolWaveletOperation_Builder*) clearMutateDocument;

- (BOOL) hasNoOp;
- (BOOL) noOp;
- (ProtocolWaveletOperation_Builder*) setNoOp:(BOOL) value;
- (ProtocolWaveletOperation_Builder*) clearNoOp;
@end

@interface ProtocolDocumentOperation : PBGeneratedMessage {
@private
  NSMutableArray* mutableComponentList;
}
- (NSArray*) componentList;
- (ProtocolDocumentOperation_Component*) componentAtIndex:(int32_t) index;

+ (ProtocolDocumentOperation*) defaultInstance;
- (ProtocolDocumentOperation*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Builder*) builder;
+ (ProtocolDocumentOperation_Builder*) builder;
+ (ProtocolDocumentOperation_Builder*) builderWithPrototype:(ProtocolDocumentOperation*) prototype;

+ (ProtocolDocumentOperation*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component : PBGeneratedMessage {
@private
  BOOL hasElementEnd_:1;
  BOOL hasDeleteElementEnd_:1;
  BOOL hasRetainItemCount_:1;
  BOOL hasCharacters_:1;
  BOOL hasDeleteCharacters_:1;
  BOOL hasAnnotationBoundary_:1;
  BOOL hasElementStart_:1;
  BOOL hasDeleteElementStart_:1;
  BOOL hasReplaceAttributes_:1;
  BOOL hasUpdateAttributes_:1;
  BOOL elementEnd_:1;
  BOOL deleteElementEnd_:1;
  int32_t retainItemCount;
  NSString* characters;
  NSString* deleteCharacters;
  ProtocolDocumentOperation_Component_AnnotationBoundary* annotationBoundary;
  ProtocolDocumentOperation_Component_ElementStart* elementStart;
  ProtocolDocumentOperation_Component_ElementStart* deleteElementStart;
  ProtocolDocumentOperation_Component_ReplaceAttributes* replaceAttributes;
  ProtocolDocumentOperation_Component_UpdateAttributes* updateAttributes;
}
- (BOOL) hasAnnotationBoundary;
- (BOOL) hasCharacters;
- (BOOL) hasElementStart;
- (BOOL) hasElementEnd;
- (BOOL) hasRetainItemCount;
- (BOOL) hasDeleteCharacters;
- (BOOL) hasDeleteElementStart;
- (BOOL) hasDeleteElementEnd;
- (BOOL) hasReplaceAttributes;
- (BOOL) hasUpdateAttributes;
@property (readonly, retain) ProtocolDocumentOperation_Component_AnnotationBoundary* annotationBoundary;
@property (readonly, retain) NSString* characters;
@property (readonly, retain) ProtocolDocumentOperation_Component_ElementStart* elementStart;
- (BOOL) elementEnd;
@property (readonly) int32_t retainItemCount;
@property (readonly, retain) NSString* deleteCharacters;
@property (readonly, retain) ProtocolDocumentOperation_Component_ElementStart* deleteElementStart;
- (BOOL) deleteElementEnd;
@property (readonly, retain) ProtocolDocumentOperation_Component_ReplaceAttributes* replaceAttributes;
@property (readonly, retain) ProtocolDocumentOperation_Component_UpdateAttributes* updateAttributes;

+ (ProtocolDocumentOperation_Component*) defaultInstance;
- (ProtocolDocumentOperation_Component*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Component_Builder*) builder;
+ (ProtocolDocumentOperation_Component_Builder*) builder;
+ (ProtocolDocumentOperation_Component_Builder*) builderWithPrototype:(ProtocolDocumentOperation_Component*) prototype;

+ (ProtocolDocumentOperation_Component*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation_Component*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation_Component*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation_Component*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component_KeyValuePair : PBGeneratedMessage {
@private
  BOOL hasKey_:1;
  BOOL hasValue_:1;
  NSString* key;
  NSString* value;
}
- (BOOL) hasKey;
- (BOOL) hasValue;
@property (readonly, retain) NSString* key;
@property (readonly, retain) NSString* value;

+ (ProtocolDocumentOperation_Component_KeyValuePair*) defaultInstance;
- (ProtocolDocumentOperation_Component_KeyValuePair*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) builder;
+ (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) builder;
+ (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) builderWithPrototype:(ProtocolDocumentOperation_Component_KeyValuePair*) prototype;

+ (ProtocolDocumentOperation_Component_KeyValuePair*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation_Component_KeyValuePair*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_KeyValuePair*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation_Component_KeyValuePair*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_KeyValuePair*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation_Component_KeyValuePair*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component_KeyValuePair_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation_Component_KeyValuePair* result;
}

- (ProtocolDocumentOperation_Component_KeyValuePair*) defaultInstance;

- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) clear;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) clone;

- (ProtocolDocumentOperation_Component_KeyValuePair*) build;
- (ProtocolDocumentOperation_Component_KeyValuePair*) buildPartial;

- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) mergeFrom:(ProtocolDocumentOperation_Component_KeyValuePair*) other;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (NSString*) key;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) setKey:(NSString*) value;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) clearKey;

- (BOOL) hasValue;
- (NSString*) value;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) setValue:(NSString*) value;
- (ProtocolDocumentOperation_Component_KeyValuePair_Builder*) clearValue;
@end

@interface ProtocolDocumentOperation_Component_KeyValueUpdate : PBGeneratedMessage {
@private
  BOOL hasKey_:1;
  BOOL hasOldValue_:1;
  BOOL hasNewValue_:1;
  NSString* key;
  NSString* oldValue;
  NSString* newValue;
}
- (BOOL) hasKey;
- (BOOL) hasOldValue;
- (BOOL) hasNewValue;
@property (readonly, retain) NSString* key;
@property (readonly, retain) NSString* oldValue;
@property (readonly, retain) NSString* newValue;

+ (ProtocolDocumentOperation_Component_KeyValueUpdate*) defaultInstance;
- (ProtocolDocumentOperation_Component_KeyValueUpdate*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) builder;
+ (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) builder;
+ (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) builderWithPrototype:(ProtocolDocumentOperation_Component_KeyValueUpdate*) prototype;

+ (ProtocolDocumentOperation_Component_KeyValueUpdate*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation_Component_KeyValueUpdate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_KeyValueUpdate*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation_Component_KeyValueUpdate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_KeyValueUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation_Component_KeyValueUpdate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component_KeyValueUpdate_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation_Component_KeyValueUpdate* result;
}

- (ProtocolDocumentOperation_Component_KeyValueUpdate*) defaultInstance;

- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) clear;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) clone;

- (ProtocolDocumentOperation_Component_KeyValueUpdate*) build;
- (ProtocolDocumentOperation_Component_KeyValueUpdate*) buildPartial;

- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) mergeFrom:(ProtocolDocumentOperation_Component_KeyValueUpdate*) other;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasKey;
- (NSString*) key;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) setKey:(NSString*) value;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) clearKey;

- (BOOL) hasOldValue;
- (NSString*) oldValue;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) setOldValue:(NSString*) value;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) clearOldValue;

- (BOOL) hasNewValue;
- (NSString*) newValue;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) setNewValue:(NSString*) value;
- (ProtocolDocumentOperation_Component_KeyValueUpdate_Builder*) clearNewValue;
@end

@interface ProtocolDocumentOperation_Component_ElementStart : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  NSString* type;
  NSMutableArray* mutableAttributeList;
}
- (BOOL) hasType;
@property (readonly, retain) NSString* type;
- (NSArray*) attributeList;
- (ProtocolDocumentOperation_Component_KeyValuePair*) attributeAtIndex:(int32_t) index;

+ (ProtocolDocumentOperation_Component_ElementStart*) defaultInstance;
- (ProtocolDocumentOperation_Component_ElementStart*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) builder;
+ (ProtocolDocumentOperation_Component_ElementStart_Builder*) builder;
+ (ProtocolDocumentOperation_Component_ElementStart_Builder*) builderWithPrototype:(ProtocolDocumentOperation_Component_ElementStart*) prototype;

+ (ProtocolDocumentOperation_Component_ElementStart*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation_Component_ElementStart*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_ElementStart*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation_Component_ElementStart*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_ElementStart*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation_Component_ElementStart*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component_ElementStart_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation_Component_ElementStart* result;
}

- (ProtocolDocumentOperation_Component_ElementStart*) defaultInstance;

- (ProtocolDocumentOperation_Component_ElementStart_Builder*) clear;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) clone;

- (ProtocolDocumentOperation_Component_ElementStart*) build;
- (ProtocolDocumentOperation_Component_ElementStart*) buildPartial;

- (ProtocolDocumentOperation_Component_ElementStart_Builder*) mergeFrom:(ProtocolDocumentOperation_Component_ElementStart*) other;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (NSString*) type;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) setType:(NSString*) value;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) clearType;

- (NSArray*) attributeList;
- (ProtocolDocumentOperation_Component_KeyValuePair*) attributeAtIndex:(int32_t) index;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) replaceAttributeAtIndex:(int32_t) index with:(ProtocolDocumentOperation_Component_KeyValuePair*) value;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) addAttribute:(ProtocolDocumentOperation_Component_KeyValuePair*) value;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) addAllAttribute:(NSArray*) values;
- (ProtocolDocumentOperation_Component_ElementStart_Builder*) clearAttributeList;
@end

@interface ProtocolDocumentOperation_Component_ReplaceAttributes : PBGeneratedMessage {
@private
  BOOL hasEmpty_:1;
  BOOL empty_:1;
  NSMutableArray* mutableOldAttributeList;
  NSMutableArray* mutableNewAttributeList;
}
- (BOOL) hasEmpty;
- (BOOL) empty;
- (NSArray*) oldAttributeList;
- (ProtocolDocumentOperation_Component_KeyValuePair*) oldAttributeAtIndex:(int32_t) index;
- (NSArray*) newAttributeList;
- (ProtocolDocumentOperation_Component_KeyValuePair*) newAttributeAtIndex:(int32_t) index;

+ (ProtocolDocumentOperation_Component_ReplaceAttributes*) defaultInstance;
- (ProtocolDocumentOperation_Component_ReplaceAttributes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) builder;
+ (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) builder;
+ (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) builderWithPrototype:(ProtocolDocumentOperation_Component_ReplaceAttributes*) prototype;

+ (ProtocolDocumentOperation_Component_ReplaceAttributes*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation_Component_ReplaceAttributes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_ReplaceAttributes*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation_Component_ReplaceAttributes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_ReplaceAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation_Component_ReplaceAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component_ReplaceAttributes_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation_Component_ReplaceAttributes* result;
}

- (ProtocolDocumentOperation_Component_ReplaceAttributes*) defaultInstance;

- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) clear;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) clone;

- (ProtocolDocumentOperation_Component_ReplaceAttributes*) build;
- (ProtocolDocumentOperation_Component_ReplaceAttributes*) buildPartial;

- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) mergeFrom:(ProtocolDocumentOperation_Component_ReplaceAttributes*) other;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEmpty;
- (BOOL) empty;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) setEmpty:(BOOL) value;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) clearEmpty;

- (NSArray*) oldAttributeList;
- (ProtocolDocumentOperation_Component_KeyValuePair*) oldAttributeAtIndex:(int32_t) index;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) replaceOldAttributeAtIndex:(int32_t) index with:(ProtocolDocumentOperation_Component_KeyValuePair*) value;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) addOldAttribute:(ProtocolDocumentOperation_Component_KeyValuePair*) value;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) addAllOldAttribute:(NSArray*) values;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) clearOldAttributeList;

- (NSArray*) newAttributeList;
- (ProtocolDocumentOperation_Component_KeyValuePair*) newAttributeAtIndex:(int32_t) index;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) replaceNewAttributeAtIndex:(int32_t) index with:(ProtocolDocumentOperation_Component_KeyValuePair*) value;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) addNewAttribute:(ProtocolDocumentOperation_Component_KeyValuePair*) value;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) addAllNewAttribute:(NSArray*) values;
- (ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) clearNewAttributeList;
@end

@interface ProtocolDocumentOperation_Component_UpdateAttributes : PBGeneratedMessage {
@private
  BOOL hasEmpty_:1;
  BOOL empty_:1;
  NSMutableArray* mutableAttributeUpdateList;
}
- (BOOL) hasEmpty;
- (BOOL) empty;
- (NSArray*) attributeUpdateList;
- (ProtocolDocumentOperation_Component_KeyValueUpdate*) attributeUpdateAtIndex:(int32_t) index;

+ (ProtocolDocumentOperation_Component_UpdateAttributes*) defaultInstance;
- (ProtocolDocumentOperation_Component_UpdateAttributes*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) builder;
+ (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) builder;
+ (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) builderWithPrototype:(ProtocolDocumentOperation_Component_UpdateAttributes*) prototype;

+ (ProtocolDocumentOperation_Component_UpdateAttributes*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation_Component_UpdateAttributes*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_UpdateAttributes*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation_Component_UpdateAttributes*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_UpdateAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation_Component_UpdateAttributes*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component_UpdateAttributes_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation_Component_UpdateAttributes* result;
}

- (ProtocolDocumentOperation_Component_UpdateAttributes*) defaultInstance;

- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) clear;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) clone;

- (ProtocolDocumentOperation_Component_UpdateAttributes*) build;
- (ProtocolDocumentOperation_Component_UpdateAttributes*) buildPartial;

- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) mergeFrom:(ProtocolDocumentOperation_Component_UpdateAttributes*) other;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEmpty;
- (BOOL) empty;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) setEmpty:(BOOL) value;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) clearEmpty;

- (NSArray*) attributeUpdateList;
- (ProtocolDocumentOperation_Component_KeyValueUpdate*) attributeUpdateAtIndex:(int32_t) index;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) replaceAttributeUpdateAtIndex:(int32_t) index with:(ProtocolDocumentOperation_Component_KeyValueUpdate*) value;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) addAttributeUpdate:(ProtocolDocumentOperation_Component_KeyValueUpdate*) value;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) addAllAttributeUpdate:(NSArray*) values;
- (ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) clearAttributeUpdateList;
@end

@interface ProtocolDocumentOperation_Component_AnnotationBoundary : PBGeneratedMessage {
@private
  BOOL hasEmpty_:1;
  BOOL empty_:1;
  NSMutableArray* mutableEndList;
  NSMutableArray* mutableChangeList;
}
- (BOOL) hasEmpty;
- (BOOL) empty;
- (NSArray*) endList;
- (NSString*) endAtIndex:(int32_t) index;
- (NSArray*) changeList;
- (ProtocolDocumentOperation_Component_KeyValueUpdate*) changeAtIndex:(int32_t) index;

+ (ProtocolDocumentOperation_Component_AnnotationBoundary*) defaultInstance;
- (ProtocolDocumentOperation_Component_AnnotationBoundary*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) builder;
+ (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) builder;
+ (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) builderWithPrototype:(ProtocolDocumentOperation_Component_AnnotationBoundary*) prototype;

+ (ProtocolDocumentOperation_Component_AnnotationBoundary*) parseFromData:(NSData*) data;
+ (ProtocolDocumentOperation_Component_AnnotationBoundary*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_AnnotationBoundary*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolDocumentOperation_Component_AnnotationBoundary*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolDocumentOperation_Component_AnnotationBoundary*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolDocumentOperation_Component_AnnotationBoundary*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolDocumentOperation_Component_AnnotationBoundary_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation_Component_AnnotationBoundary* result;
}

- (ProtocolDocumentOperation_Component_AnnotationBoundary*) defaultInstance;

- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) clear;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) clone;

- (ProtocolDocumentOperation_Component_AnnotationBoundary*) build;
- (ProtocolDocumentOperation_Component_AnnotationBoundary*) buildPartial;

- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) mergeFrom:(ProtocolDocumentOperation_Component_AnnotationBoundary*) other;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEmpty;
- (BOOL) empty;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) setEmpty:(BOOL) value;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) clearEmpty;

- (NSArray*) endList;
- (NSString*) endAtIndex:(int32_t) index;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) replaceEndAtIndex:(int32_t) index with:(NSString*) value;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) addEnd:(NSString*) value;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) addAllEnd:(NSArray*) values;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) clearEndList;

- (NSArray*) changeList;
- (ProtocolDocumentOperation_Component_KeyValueUpdate*) changeAtIndex:(int32_t) index;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) replaceChangeAtIndex:(int32_t) index with:(ProtocolDocumentOperation_Component_KeyValueUpdate*) value;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) addChange:(ProtocolDocumentOperation_Component_KeyValueUpdate*) value;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) addAllChange:(NSArray*) values;
- (ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) clearChangeList;
@end

@interface ProtocolDocumentOperation_Component_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation_Component* result;
}

- (ProtocolDocumentOperation_Component*) defaultInstance;

- (ProtocolDocumentOperation_Component_Builder*) clear;
- (ProtocolDocumentOperation_Component_Builder*) clone;

- (ProtocolDocumentOperation_Component*) build;
- (ProtocolDocumentOperation_Component*) buildPartial;

- (ProtocolDocumentOperation_Component_Builder*) mergeFrom:(ProtocolDocumentOperation_Component*) other;
- (ProtocolDocumentOperation_Component_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Component_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAnnotationBoundary;
- (ProtocolDocumentOperation_Component_AnnotationBoundary*) annotationBoundary;
- (ProtocolDocumentOperation_Component_Builder*) setAnnotationBoundary:(ProtocolDocumentOperation_Component_AnnotationBoundary*) value;
- (ProtocolDocumentOperation_Component_Builder*) setAnnotationBoundaryBuilder:(ProtocolDocumentOperation_Component_AnnotationBoundary_Builder*) builderForValue;
- (ProtocolDocumentOperation_Component_Builder*) mergeAnnotationBoundary:(ProtocolDocumentOperation_Component_AnnotationBoundary*) value;
- (ProtocolDocumentOperation_Component_Builder*) clearAnnotationBoundary;

- (BOOL) hasCharacters;
- (NSString*) characters;
- (ProtocolDocumentOperation_Component_Builder*) setCharacters:(NSString*) value;
- (ProtocolDocumentOperation_Component_Builder*) clearCharacters;

- (BOOL) hasElementStart;
- (ProtocolDocumentOperation_Component_ElementStart*) elementStart;
- (ProtocolDocumentOperation_Component_Builder*) setElementStart:(ProtocolDocumentOperation_Component_ElementStart*) value;
- (ProtocolDocumentOperation_Component_Builder*) setElementStartBuilder:(ProtocolDocumentOperation_Component_ElementStart_Builder*) builderForValue;
- (ProtocolDocumentOperation_Component_Builder*) mergeElementStart:(ProtocolDocumentOperation_Component_ElementStart*) value;
- (ProtocolDocumentOperation_Component_Builder*) clearElementStart;

- (BOOL) hasElementEnd;
- (BOOL) elementEnd;
- (ProtocolDocumentOperation_Component_Builder*) setElementEnd:(BOOL) value;
- (ProtocolDocumentOperation_Component_Builder*) clearElementEnd;

- (BOOL) hasRetainItemCount;
- (int32_t) retainItemCount;
- (ProtocolDocumentOperation_Component_Builder*) setRetainItemCount:(int32_t) value;
- (ProtocolDocumentOperation_Component_Builder*) clearRetainItemCount;

- (BOOL) hasDeleteCharacters;
- (NSString*) deleteCharacters;
- (ProtocolDocumentOperation_Component_Builder*) setDeleteCharacters:(NSString*) value;
- (ProtocolDocumentOperation_Component_Builder*) clearDeleteCharacters;

- (BOOL) hasDeleteElementStart;
- (ProtocolDocumentOperation_Component_ElementStart*) deleteElementStart;
- (ProtocolDocumentOperation_Component_Builder*) setDeleteElementStart:(ProtocolDocumentOperation_Component_ElementStart*) value;
- (ProtocolDocumentOperation_Component_Builder*) setDeleteElementStartBuilder:(ProtocolDocumentOperation_Component_ElementStart_Builder*) builderForValue;
- (ProtocolDocumentOperation_Component_Builder*) mergeDeleteElementStart:(ProtocolDocumentOperation_Component_ElementStart*) value;
- (ProtocolDocumentOperation_Component_Builder*) clearDeleteElementStart;

- (BOOL) hasDeleteElementEnd;
- (BOOL) deleteElementEnd;
- (ProtocolDocumentOperation_Component_Builder*) setDeleteElementEnd:(BOOL) value;
- (ProtocolDocumentOperation_Component_Builder*) clearDeleteElementEnd;

- (BOOL) hasReplaceAttributes;
- (ProtocolDocumentOperation_Component_ReplaceAttributes*) replaceAttributes;
- (ProtocolDocumentOperation_Component_Builder*) setReplaceAttributes:(ProtocolDocumentOperation_Component_ReplaceAttributes*) value;
- (ProtocolDocumentOperation_Component_Builder*) setReplaceAttributesBuilder:(ProtocolDocumentOperation_Component_ReplaceAttributes_Builder*) builderForValue;
- (ProtocolDocumentOperation_Component_Builder*) mergeReplaceAttributes:(ProtocolDocumentOperation_Component_ReplaceAttributes*) value;
- (ProtocolDocumentOperation_Component_Builder*) clearReplaceAttributes;

- (BOOL) hasUpdateAttributes;
- (ProtocolDocumentOperation_Component_UpdateAttributes*) updateAttributes;
- (ProtocolDocumentOperation_Component_Builder*) setUpdateAttributes:(ProtocolDocumentOperation_Component_UpdateAttributes*) value;
- (ProtocolDocumentOperation_Component_Builder*) setUpdateAttributesBuilder:(ProtocolDocumentOperation_Component_UpdateAttributes_Builder*) builderForValue;
- (ProtocolDocumentOperation_Component_Builder*) mergeUpdateAttributes:(ProtocolDocumentOperation_Component_UpdateAttributes*) value;
- (ProtocolDocumentOperation_Component_Builder*) clearUpdateAttributes;
@end

@interface ProtocolDocumentOperation_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolDocumentOperation* result;
}

- (ProtocolDocumentOperation*) defaultInstance;

- (ProtocolDocumentOperation_Builder*) clear;
- (ProtocolDocumentOperation_Builder*) clone;

- (ProtocolDocumentOperation*) build;
- (ProtocolDocumentOperation*) buildPartial;

- (ProtocolDocumentOperation_Builder*) mergeFrom:(ProtocolDocumentOperation*) other;
- (ProtocolDocumentOperation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolDocumentOperation_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) componentList;
- (ProtocolDocumentOperation_Component*) componentAtIndex:(int32_t) index;
- (ProtocolDocumentOperation_Builder*) replaceComponentAtIndex:(int32_t) index with:(ProtocolDocumentOperation_Component*) value;
- (ProtocolDocumentOperation_Builder*) addComponent:(ProtocolDocumentOperation_Component*) value;
- (ProtocolDocumentOperation_Builder*) addAllComponent:(NSArray*) values;
- (ProtocolDocumentOperation_Builder*) clearComponentList;
@end

@interface ProtocolAppliedWaveletDelta : PBGeneratedMessage {
@private
  BOOL hasApplicationTimestamp_:1;
  BOOL hasOperationsApplied_:1;
  BOOL hasSignedOriginalDelta_:1;
  BOOL hasHashedVersionAppliedAt_:1;
  int64_t applicationTimestamp;
  int32_t operationsApplied;
  ProtocolSignedDelta* signedOriginalDelta;
  ProtocolHashedVersion* hashedVersionAppliedAt;
}
- (BOOL) hasSignedOriginalDelta;
- (BOOL) hasHashedVersionAppliedAt;
- (BOOL) hasOperationsApplied;
- (BOOL) hasApplicationTimestamp;
@property (readonly, retain) ProtocolSignedDelta* signedOriginalDelta;
@property (readonly, retain) ProtocolHashedVersion* hashedVersionAppliedAt;
@property (readonly) int32_t operationsApplied;
@property (readonly) int64_t applicationTimestamp;

+ (ProtocolAppliedWaveletDelta*) defaultInstance;
- (ProtocolAppliedWaveletDelta*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolAppliedWaveletDelta_Builder*) builder;
+ (ProtocolAppliedWaveletDelta_Builder*) builder;
+ (ProtocolAppliedWaveletDelta_Builder*) builderWithPrototype:(ProtocolAppliedWaveletDelta*) prototype;

+ (ProtocolAppliedWaveletDelta*) parseFromData:(NSData*) data;
+ (ProtocolAppliedWaveletDelta*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolAppliedWaveletDelta*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolAppliedWaveletDelta*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolAppliedWaveletDelta*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolAppliedWaveletDelta*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolAppliedWaveletDelta_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolAppliedWaveletDelta* result;
}

- (ProtocolAppliedWaveletDelta*) defaultInstance;

- (ProtocolAppliedWaveletDelta_Builder*) clear;
- (ProtocolAppliedWaveletDelta_Builder*) clone;

- (ProtocolAppliedWaveletDelta*) build;
- (ProtocolAppliedWaveletDelta*) buildPartial;

- (ProtocolAppliedWaveletDelta_Builder*) mergeFrom:(ProtocolAppliedWaveletDelta*) other;
- (ProtocolAppliedWaveletDelta_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolAppliedWaveletDelta_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSignedOriginalDelta;
- (ProtocolSignedDelta*) signedOriginalDelta;
- (ProtocolAppliedWaveletDelta_Builder*) setSignedOriginalDelta:(ProtocolSignedDelta*) value;
- (ProtocolAppliedWaveletDelta_Builder*) setSignedOriginalDeltaBuilder:(ProtocolSignedDelta_Builder*) builderForValue;
- (ProtocolAppliedWaveletDelta_Builder*) mergeSignedOriginalDelta:(ProtocolSignedDelta*) value;
- (ProtocolAppliedWaveletDelta_Builder*) clearSignedOriginalDelta;

- (BOOL) hasHashedVersionAppliedAt;
- (ProtocolHashedVersion*) hashedVersionAppliedAt;
- (ProtocolAppliedWaveletDelta_Builder*) setHashedVersionAppliedAt:(ProtocolHashedVersion*) value;
- (ProtocolAppliedWaveletDelta_Builder*) setHashedVersionAppliedAtBuilder:(ProtocolHashedVersion_Builder*) builderForValue;
- (ProtocolAppliedWaveletDelta_Builder*) mergeHashedVersionAppliedAt:(ProtocolHashedVersion*) value;
- (ProtocolAppliedWaveletDelta_Builder*) clearHashedVersionAppliedAt;

- (BOOL) hasOperationsApplied;
- (int32_t) operationsApplied;
- (ProtocolAppliedWaveletDelta_Builder*) setOperationsApplied:(int32_t) value;
- (ProtocolAppliedWaveletDelta_Builder*) clearOperationsApplied;

- (BOOL) hasApplicationTimestamp;
- (int64_t) applicationTimestamp;
- (ProtocolAppliedWaveletDelta_Builder*) setApplicationTimestamp:(int64_t) value;
- (ProtocolAppliedWaveletDelta_Builder*) clearApplicationTimestamp;
@end

@interface ProtocolSignedDelta : PBGeneratedMessage {
@private
  BOOL hasDelta_:1;
  NSData* delta;
  NSMutableArray* mutableSignatureList;
}
- (BOOL) hasDelta;
@property (readonly, retain) NSData* delta;
- (NSArray*) signatureList;
- (ProtocolSignature*) signatureAtIndex:(int32_t) index;

+ (ProtocolSignedDelta*) defaultInstance;
- (ProtocolSignedDelta*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolSignedDelta_Builder*) builder;
+ (ProtocolSignedDelta_Builder*) builder;
+ (ProtocolSignedDelta_Builder*) builderWithPrototype:(ProtocolSignedDelta*) prototype;

+ (ProtocolSignedDelta*) parseFromData:(NSData*) data;
+ (ProtocolSignedDelta*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolSignedDelta*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolSignedDelta*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolSignedDelta*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolSignedDelta*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolSignedDelta_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolSignedDelta* result;
}

- (ProtocolSignedDelta*) defaultInstance;

- (ProtocolSignedDelta_Builder*) clear;
- (ProtocolSignedDelta_Builder*) clone;

- (ProtocolSignedDelta*) build;
- (ProtocolSignedDelta*) buildPartial;

- (ProtocolSignedDelta_Builder*) mergeFrom:(ProtocolSignedDelta*) other;
- (ProtocolSignedDelta_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolSignedDelta_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDelta;
- (NSData*) delta;
- (ProtocolSignedDelta_Builder*) setDelta:(NSData*) value;
- (ProtocolSignedDelta_Builder*) clearDelta;

- (NSArray*) signatureList;
- (ProtocolSignature*) signatureAtIndex:(int32_t) index;
- (ProtocolSignedDelta_Builder*) replaceSignatureAtIndex:(int32_t) index with:(ProtocolSignature*) value;
- (ProtocolSignedDelta_Builder*) addSignature:(ProtocolSignature*) value;
- (ProtocolSignedDelta_Builder*) addAllSignature:(NSArray*) values;
- (ProtocolSignedDelta_Builder*) clearSignatureList;
@end

@interface ProtocolSignature : PBGeneratedMessage {
@private
  BOOL hasSignatureBytes_:1;
  BOOL hasSignerId_:1;
  BOOL hasSignatureAlgorithm_:1;
  NSData* signatureBytes;
  NSData* signerId;
  ProtocolSignature_SignatureAlgorithm signatureAlgorithm;
}
- (BOOL) hasSignatureBytes;
- (BOOL) hasSignerId;
- (BOOL) hasSignatureAlgorithm;
@property (readonly, retain) NSData* signatureBytes;
@property (readonly, retain) NSData* signerId;
@property (readonly) ProtocolSignature_SignatureAlgorithm signatureAlgorithm;

+ (ProtocolSignature*) defaultInstance;
- (ProtocolSignature*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolSignature_Builder*) builder;
+ (ProtocolSignature_Builder*) builder;
+ (ProtocolSignature_Builder*) builderWithPrototype:(ProtocolSignature*) prototype;

+ (ProtocolSignature*) parseFromData:(NSData*) data;
+ (ProtocolSignature*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolSignature*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolSignature*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolSignature*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolSignature*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolSignature_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolSignature* result;
}

- (ProtocolSignature*) defaultInstance;

- (ProtocolSignature_Builder*) clear;
- (ProtocolSignature_Builder*) clone;

- (ProtocolSignature*) build;
- (ProtocolSignature*) buildPartial;

- (ProtocolSignature_Builder*) mergeFrom:(ProtocolSignature*) other;
- (ProtocolSignature_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolSignature_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSignatureBytes;
- (NSData*) signatureBytes;
- (ProtocolSignature_Builder*) setSignatureBytes:(NSData*) value;
- (ProtocolSignature_Builder*) clearSignatureBytes;

- (BOOL) hasSignerId;
- (NSData*) signerId;
- (ProtocolSignature_Builder*) setSignerId:(NSData*) value;
- (ProtocolSignature_Builder*) clearSignerId;

- (BOOL) hasSignatureAlgorithm;
- (ProtocolSignature_SignatureAlgorithm) signatureAlgorithm;
- (ProtocolSignature_Builder*) setSignatureAlgorithm:(ProtocolSignature_SignatureAlgorithm) value;
- (ProtocolSignature_Builder*) clearSignatureAlgorithm;
@end

@interface ProtocolSignerInfo : PBGeneratedMessage {
@private
  BOOL hasDomain_:1;
  BOOL hasHashAlgorithm_:1;
  NSString* domain;
  ProtocolSignerInfo_HashAlgorithm hashAlgorithm;
  NSMutableArray* mutableCertificateList;
}
- (BOOL) hasHashAlgorithm;
- (BOOL) hasDomain;
@property (readonly) ProtocolSignerInfo_HashAlgorithm hashAlgorithm;
@property (readonly, retain) NSString* domain;
- (NSArray*) certificateList;
- (NSData*) certificateAtIndex:(int32_t) index;

+ (ProtocolSignerInfo*) defaultInstance;
- (ProtocolSignerInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolSignerInfo_Builder*) builder;
+ (ProtocolSignerInfo_Builder*) builder;
+ (ProtocolSignerInfo_Builder*) builderWithPrototype:(ProtocolSignerInfo*) prototype;

+ (ProtocolSignerInfo*) parseFromData:(NSData*) data;
+ (ProtocolSignerInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolSignerInfo*) parseFromInputStream:(NSInputStream*) input;
+ (ProtocolSignerInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ProtocolSignerInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ProtocolSignerInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolSignerInfo_Builder : PBGeneratedMessage_Builder {
@private
  ProtocolSignerInfo* result;
}

- (ProtocolSignerInfo*) defaultInstance;

- (ProtocolSignerInfo_Builder*) clear;
- (ProtocolSignerInfo_Builder*) clone;

- (ProtocolSignerInfo*) build;
- (ProtocolSignerInfo*) buildPartial;

- (ProtocolSignerInfo_Builder*) mergeFrom:(ProtocolSignerInfo*) other;
- (ProtocolSignerInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolSignerInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasHashAlgorithm;
- (ProtocolSignerInfo_HashAlgorithm) hashAlgorithm;
- (ProtocolSignerInfo_Builder*) setHashAlgorithm:(ProtocolSignerInfo_HashAlgorithm) value;
- (ProtocolSignerInfo_Builder*) clearHashAlgorithm;

- (BOOL) hasDomain;
- (NSString*) domain;
- (ProtocolSignerInfo_Builder*) setDomain:(NSString*) value;
- (ProtocolSignerInfo_Builder*) clearDomain;

- (NSArray*) certificateList;
- (NSData*) certificateAtIndex:(int32_t) index;
- (ProtocolSignerInfo_Builder*) replaceCertificateAtIndex:(int32_t) index with:(NSData*) value;
- (ProtocolSignerInfo_Builder*) addCertificate:(NSData*) value;
- (ProtocolSignerInfo_Builder*) addAllCertificate:(NSArray*) values;
- (ProtocolSignerInfo_Builder*) clearCertificateList;
@end

