// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class DescriptorProto;
@class DescriptorProto_Builder;
@class DescriptorProto_ExtensionRange;
@class DescriptorProto_ExtensionRange_Builder;
@class EnumDescriptorProto;
@class EnumDescriptorProto_Builder;
@class EnumOptions;
@class EnumOptions_Builder;
@class EnumValueDescriptorProto;
@class EnumValueDescriptorProto_Builder;
@class EnumValueOptions;
@class EnumValueOptions_Builder;
@class FieldDescriptorProto;
@class FieldDescriptorProto_Builder;
@class FieldOptions;
@class FieldOptions_Builder;
@class FileDescriptorProto;
@class FileDescriptorProto_Builder;
@class FileDescriptorSet;
@class FileDescriptorSet_Builder;
@class FileOptions;
@class FileOptions_Builder;
@class MessageOptions;
@class MessageOptions_Builder;
@class MethodDescriptorProto;
@class MethodDescriptorProto_Builder;
@class MethodOptions;
@class MethodOptions_Builder;
@class ServiceDescriptorProto;
@class ServiceDescriptorProto_Builder;
@class ServiceOptions;
@class ServiceOptions_Builder;
@class UninterpretedOption;
@class UninterpretedOption_Builder;
@class UninterpretedOption_NamePart;
@class UninterpretedOption_NamePart_Builder;
typedef enum {
  FieldDescriptorProto_TypeTypeDouble = 1,
  FieldDescriptorProto_TypeTypeFloat = 2,
  FieldDescriptorProto_TypeTypeInt64 = 3,
  FieldDescriptorProto_TypeTypeUint64 = 4,
  FieldDescriptorProto_TypeTypeInt32 = 5,
  FieldDescriptorProto_TypeTypeFixed64 = 6,
  FieldDescriptorProto_TypeTypeFixed32 = 7,
  FieldDescriptorProto_TypeTypeBool = 8,
  FieldDescriptorProto_TypeTypeString = 9,
  FieldDescriptorProto_TypeTypeGroup = 10,
  FieldDescriptorProto_TypeTypeMessage = 11,
  FieldDescriptorProto_TypeTypeBytes = 12,
  FieldDescriptorProto_TypeTypeUint32 = 13,
  FieldDescriptorProto_TypeTypeEnum = 14,
  FieldDescriptorProto_TypeTypeSfixed32 = 15,
  FieldDescriptorProto_TypeTypeSfixed64 = 16,
  FieldDescriptorProto_TypeTypeSint32 = 17,
  FieldDescriptorProto_TypeTypeSint64 = 18,
} FieldDescriptorProto_Type;

BOOL FieldDescriptorProto_TypeIsValidValue(FieldDescriptorProto_Type value);

typedef enum {
  FieldDescriptorProto_LabelLabelOptional = 1,
  FieldDescriptorProto_LabelLabelRequired = 2,
  FieldDescriptorProto_LabelLabelRepeated = 3,
} FieldDescriptorProto_Label;

BOOL FieldDescriptorProto_LabelIsValidValue(FieldDescriptorProto_Label value);

typedef enum {
  FileOptions_OptimizeModeSpeed = 1,
  FileOptions_OptimizeModeCodeSize = 2,
  FileOptions_OptimizeModeLiteRuntime = 3,
} FileOptions_OptimizeMode;

BOOL FileOptions_OptimizeModeIsValidValue(FileOptions_OptimizeMode value);

typedef enum {
  FieldOptions_CTypeCord = 1,
  FieldOptions_CTypeStringPiece = 2,
} FieldOptions_CType;

BOOL FieldOptions_CTypeIsValidValue(FieldOptions_CType value);


@interface DescriptorRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface FileDescriptorSet : PBGeneratedMessage {
@private
  NSMutableArray* mutableFileList;
}
- (NSArray*) fileList;
- (FileDescriptorProto*) fileAtIndex:(int32_t) index;

+ (FileDescriptorSet*) defaultInstance;
- (FileDescriptorSet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileDescriptorSet_Builder*) builder;
+ (FileDescriptorSet_Builder*) builder;
+ (FileDescriptorSet_Builder*) builderWithPrototype:(FileDescriptorSet*) prototype;

+ (FileDescriptorSet*) parseFromData:(NSData*) data;
+ (FileDescriptorSet*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileDescriptorSet*) parseFromInputStream:(NSInputStream*) input;
+ (FileDescriptorSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileDescriptorSet*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileDescriptorSet*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileDescriptorSet_Builder : PBGeneratedMessage_Builder {
@private
  FileDescriptorSet* result;
}

- (FileDescriptorSet*) defaultInstance;

- (FileDescriptorSet_Builder*) clear;
- (FileDescriptorSet_Builder*) clone;

- (FileDescriptorSet*) build;
- (FileDescriptorSet*) buildPartial;

- (FileDescriptorSet_Builder*) mergeFrom:(FileDescriptorSet*) other;
- (FileDescriptorSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileDescriptorSet_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) fileList;
- (FileDescriptorProto*) fileAtIndex:(int32_t) index;
- (FileDescriptorSet_Builder*) replaceFileAtIndex:(int32_t) index with:(FileDescriptorProto*) value;
- (FileDescriptorSet_Builder*) addFile:(FileDescriptorProto*) value;
- (FileDescriptorSet_Builder*) addAllFile:(NSArray*) values;
- (FileDescriptorSet_Builder*) clearFileList;
@end

@interface FileDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasPackage_:1;
  BOOL hasOptions_:1;
  NSString* name;
  NSString* package;
  FileOptions* options;
  NSMutableArray* mutableDependencyList;
  NSMutableArray* mutableMessageTypeList;
  NSMutableArray* mutableEnumTypeList;
  NSMutableArray* mutableServiceList;
  NSMutableArray* mutableExtensionList;
}
- (BOOL) hasName;
- (BOOL) hasPackage;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* package;
@property (readonly, retain) FileOptions* options;
- (NSArray*) dependencyList;
- (NSString*) dependencyAtIndex:(int32_t) index;
- (NSArray*) messageTypeList;
- (DescriptorProto*) messageTypeAtIndex:(int32_t) index;
- (NSArray*) enumTypeList;
- (EnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (NSArray*) serviceList;
- (ServiceDescriptorProto*) serviceAtIndex:(int32_t) index;
- (NSArray*) extensionList;
- (FieldDescriptorProto*) extensionAtIndex:(int32_t) index;

+ (FileDescriptorProto*) defaultInstance;
- (FileDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileDescriptorProto_Builder*) builder;
+ (FileDescriptorProto_Builder*) builder;
+ (FileDescriptorProto_Builder*) builderWithPrototype:(FileDescriptorProto*) prototype;

+ (FileDescriptorProto*) parseFromData:(NSData*) data;
+ (FileDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (FileDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  FileDescriptorProto* result;
}

- (FileDescriptorProto*) defaultInstance;

- (FileDescriptorProto_Builder*) clear;
- (FileDescriptorProto_Builder*) clone;

- (FileDescriptorProto*) build;
- (FileDescriptorProto*) buildPartial;

- (FileDescriptorProto_Builder*) mergeFrom:(FileDescriptorProto*) other;
- (FileDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (FileDescriptorProto_Builder*) setName:(NSString*) value;
- (FileDescriptorProto_Builder*) clearName;

- (BOOL) hasPackage;
- (NSString*) package;
- (FileDescriptorProto_Builder*) setPackage:(NSString*) value;
- (FileDescriptorProto_Builder*) clearPackage;

- (NSArray*) dependencyList;
- (NSString*) dependencyAtIndex:(int32_t) index;
- (FileDescriptorProto_Builder*) replaceDependencyAtIndex:(int32_t) index with:(NSString*) value;
- (FileDescriptorProto_Builder*) addDependency:(NSString*) value;
- (FileDescriptorProto_Builder*) addAllDependency:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearDependencyList;

- (NSArray*) messageTypeList;
- (DescriptorProto*) messageTypeAtIndex:(int32_t) index;
- (FileDescriptorProto_Builder*) replaceMessageTypeAtIndex:(int32_t) index with:(DescriptorProto*) value;
- (FileDescriptorProto_Builder*) addMessageType:(DescriptorProto*) value;
- (FileDescriptorProto_Builder*) addAllMessageType:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearMessageTypeList;

- (NSArray*) enumTypeList;
- (EnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (FileDescriptorProto_Builder*) replaceEnumTypeAtIndex:(int32_t) index with:(EnumDescriptorProto*) value;
- (FileDescriptorProto_Builder*) addEnumType:(EnumDescriptorProto*) value;
- (FileDescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearEnumTypeList;

- (NSArray*) serviceList;
- (ServiceDescriptorProto*) serviceAtIndex:(int32_t) index;
- (FileDescriptorProto_Builder*) replaceServiceAtIndex:(int32_t) index with:(ServiceDescriptorProto*) value;
- (FileDescriptorProto_Builder*) addService:(ServiceDescriptorProto*) value;
- (FileDescriptorProto_Builder*) addAllService:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearServiceList;

- (NSArray*) extensionList;
- (FieldDescriptorProto*) extensionAtIndex:(int32_t) index;
- (FileDescriptorProto_Builder*) replaceExtensionAtIndex:(int32_t) index with:(FieldDescriptorProto*) value;
- (FileDescriptorProto_Builder*) addExtension:(FieldDescriptorProto*) value;
- (FileDescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (FileDescriptorProto_Builder*) clearExtensionList;

- (BOOL) hasOptions;
- (FileOptions*) options;
- (FileDescriptorProto_Builder*) setOptions:(FileOptions*) value;
- (FileDescriptorProto_Builder*) setOptionsBuilder:(FileOptions_Builder*) builderForValue;
- (FileDescriptorProto_Builder*) mergeOptions:(FileOptions*) value;
- (FileDescriptorProto_Builder*) clearOptions;
@end

@interface DescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  MessageOptions* options;
  NSMutableArray* mutableFieldList;
  NSMutableArray* mutableExtensionList;
  NSMutableArray* mutableNestedTypeList;
  NSMutableArray* mutableEnumTypeList;
  NSMutableArray* mutableExtensionRangeList;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) MessageOptions* options;
- (NSArray*) fieldList;
- (FieldDescriptorProto*) fieldAtIndex:(int32_t) index;
- (NSArray*) extensionList;
- (FieldDescriptorProto*) extensionAtIndex:(int32_t) index;
- (NSArray*) nestedTypeList;
- (DescriptorProto*) nestedTypeAtIndex:(int32_t) index;
- (NSArray*) enumTypeList;
- (EnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (NSArray*) extensionRangeList;
- (DescriptorProto_ExtensionRange*) extensionRangeAtIndex:(int32_t) index;

+ (DescriptorProto*) defaultInstance;
- (DescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DescriptorProto_Builder*) builder;
+ (DescriptorProto_Builder*) builder;
+ (DescriptorProto_Builder*) builderWithPrototype:(DescriptorProto*) prototype;

+ (DescriptorProto*) parseFromData:(NSData*) data;
+ (DescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (DescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DescriptorProto_ExtensionRange : PBGeneratedMessage {
@private
  BOOL hasStart_:1;
  BOOL hasEnd_:1;
  int32_t start;
  int32_t end;
}
- (BOOL) hasStart;
- (BOOL) hasEnd;
@property (readonly) int32_t start;
@property (readonly) int32_t end;

+ (DescriptorProto_ExtensionRange*) defaultInstance;
- (DescriptorProto_ExtensionRange*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DescriptorProto_ExtensionRange_Builder*) builder;
+ (DescriptorProto_ExtensionRange_Builder*) builder;
+ (DescriptorProto_ExtensionRange_Builder*) builderWithPrototype:(DescriptorProto_ExtensionRange*) prototype;

+ (DescriptorProto_ExtensionRange*) parseFromData:(NSData*) data;
+ (DescriptorProto_ExtensionRange*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DescriptorProto_ExtensionRange*) parseFromInputStream:(NSInputStream*) input;
+ (DescriptorProto_ExtensionRange*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DescriptorProto_ExtensionRange*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DescriptorProto_ExtensionRange*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DescriptorProto_ExtensionRange_Builder : PBGeneratedMessage_Builder {
@private
  DescriptorProto_ExtensionRange* result;
}

- (DescriptorProto_ExtensionRange*) defaultInstance;

- (DescriptorProto_ExtensionRange_Builder*) clear;
- (DescriptorProto_ExtensionRange_Builder*) clone;

- (DescriptorProto_ExtensionRange*) build;
- (DescriptorProto_ExtensionRange*) buildPartial;

- (DescriptorProto_ExtensionRange_Builder*) mergeFrom:(DescriptorProto_ExtensionRange*) other;
- (DescriptorProto_ExtensionRange_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DescriptorProto_ExtensionRange_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStart;
- (int32_t) start;
- (DescriptorProto_ExtensionRange_Builder*) setStart:(int32_t) value;
- (DescriptorProto_ExtensionRange_Builder*) clearStart;

- (BOOL) hasEnd;
- (int32_t) end;
- (DescriptorProto_ExtensionRange_Builder*) setEnd:(int32_t) value;
- (DescriptorProto_ExtensionRange_Builder*) clearEnd;
@end

@interface DescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  DescriptorProto* result;
}

- (DescriptorProto*) defaultInstance;

- (DescriptorProto_Builder*) clear;
- (DescriptorProto_Builder*) clone;

- (DescriptorProto*) build;
- (DescriptorProto*) buildPartial;

- (DescriptorProto_Builder*) mergeFrom:(DescriptorProto*) other;
- (DescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (DescriptorProto_Builder*) setName:(NSString*) value;
- (DescriptorProto_Builder*) clearName;

- (NSArray*) fieldList;
- (FieldDescriptorProto*) fieldAtIndex:(int32_t) index;
- (DescriptorProto_Builder*) replaceFieldAtIndex:(int32_t) index with:(FieldDescriptorProto*) value;
- (DescriptorProto_Builder*) addField:(FieldDescriptorProto*) value;
- (DescriptorProto_Builder*) addAllField:(NSArray*) values;
- (DescriptorProto_Builder*) clearFieldList;

- (NSArray*) extensionList;
- (FieldDescriptorProto*) extensionAtIndex:(int32_t) index;
- (DescriptorProto_Builder*) replaceExtensionAtIndex:(int32_t) index with:(FieldDescriptorProto*) value;
- (DescriptorProto_Builder*) addExtension:(FieldDescriptorProto*) value;
- (DescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (DescriptorProto_Builder*) clearExtensionList;

- (NSArray*) nestedTypeList;
- (DescriptorProto*) nestedTypeAtIndex:(int32_t) index;
- (DescriptorProto_Builder*) replaceNestedTypeAtIndex:(int32_t) index with:(DescriptorProto*) value;
- (DescriptorProto_Builder*) addNestedType:(DescriptorProto*) value;
- (DescriptorProto_Builder*) addAllNestedType:(NSArray*) values;
- (DescriptorProto_Builder*) clearNestedTypeList;

- (NSArray*) enumTypeList;
- (EnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (DescriptorProto_Builder*) replaceEnumTypeAtIndex:(int32_t) index with:(EnumDescriptorProto*) value;
- (DescriptorProto_Builder*) addEnumType:(EnumDescriptorProto*) value;
- (DescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (DescriptorProto_Builder*) clearEnumTypeList;

- (NSArray*) extensionRangeList;
- (DescriptorProto_ExtensionRange*) extensionRangeAtIndex:(int32_t) index;
- (DescriptorProto_Builder*) replaceExtensionRangeAtIndex:(int32_t) index with:(DescriptorProto_ExtensionRange*) value;
- (DescriptorProto_Builder*) addExtensionRange:(DescriptorProto_ExtensionRange*) value;
- (DescriptorProto_Builder*) addAllExtensionRange:(NSArray*) values;
- (DescriptorProto_Builder*) clearExtensionRangeList;

- (BOOL) hasOptions;
- (MessageOptions*) options;
- (DescriptorProto_Builder*) setOptions:(MessageOptions*) value;
- (DescriptorProto_Builder*) setOptionsBuilder:(MessageOptions_Builder*) builderForValue;
- (DescriptorProto_Builder*) mergeOptions:(MessageOptions*) value;
- (DescriptorProto_Builder*) clearOptions;
@end

@interface FieldDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasName_:1;
  BOOL hasTypeName_:1;
  BOOL hasExtendee_:1;
  BOOL hasDefaultValue_:1;
  BOOL hasOptions_:1;
  BOOL hasLabel_:1;
  BOOL hasType_:1;
  int32_t number;
  NSString* name;
  NSString* typeName;
  NSString* extendee;
  NSString* defaultValue;
  FieldOptions* options;
  FieldDescriptorProto_Label label;
  FieldDescriptorProto_Type type;
}
- (BOOL) hasName;
- (BOOL) hasNumber;
- (BOOL) hasLabel;
- (BOOL) hasType;
- (BOOL) hasTypeName;
- (BOOL) hasExtendee;
- (BOOL) hasDefaultValue;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t number;
@property (readonly) FieldDescriptorProto_Label label;
@property (readonly) FieldDescriptorProto_Type type;
@property (readonly, retain) NSString* typeName;
@property (readonly, retain) NSString* extendee;
@property (readonly, retain) NSString* defaultValue;
@property (readonly, retain) FieldOptions* options;

+ (FieldDescriptorProto*) defaultInstance;
- (FieldDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FieldDescriptorProto_Builder*) builder;
+ (FieldDescriptorProto_Builder*) builder;
+ (FieldDescriptorProto_Builder*) builderWithPrototype:(FieldDescriptorProto*) prototype;

+ (FieldDescriptorProto*) parseFromData:(NSData*) data;
+ (FieldDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (FieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FieldDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FieldDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FieldDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  FieldDescriptorProto* result;
}

- (FieldDescriptorProto*) defaultInstance;

- (FieldDescriptorProto_Builder*) clear;
- (FieldDescriptorProto_Builder*) clone;

- (FieldDescriptorProto*) build;
- (FieldDescriptorProto*) buildPartial;

- (FieldDescriptorProto_Builder*) mergeFrom:(FieldDescriptorProto*) other;
- (FieldDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FieldDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (FieldDescriptorProto_Builder*) setName:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearName;

- (BOOL) hasNumber;
- (int32_t) number;
- (FieldDescriptorProto_Builder*) setNumber:(int32_t) value;
- (FieldDescriptorProto_Builder*) clearNumber;

- (BOOL) hasLabel;
- (FieldDescriptorProto_Label) label;
- (FieldDescriptorProto_Builder*) setLabel:(FieldDescriptorProto_Label) value;
- (FieldDescriptorProto_Builder*) clearLabel;

- (BOOL) hasType;
- (FieldDescriptorProto_Type) type;
- (FieldDescriptorProto_Builder*) setType:(FieldDescriptorProto_Type) value;
- (FieldDescriptorProto_Builder*) clearType;

- (BOOL) hasTypeName;
- (NSString*) typeName;
- (FieldDescriptorProto_Builder*) setTypeName:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearTypeName;

- (BOOL) hasExtendee;
- (NSString*) extendee;
- (FieldDescriptorProto_Builder*) setExtendee:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearExtendee;

- (BOOL) hasDefaultValue;
- (NSString*) defaultValue;
- (FieldDescriptorProto_Builder*) setDefaultValue:(NSString*) value;
- (FieldDescriptorProto_Builder*) clearDefaultValue;

- (BOOL) hasOptions;
- (FieldOptions*) options;
- (FieldDescriptorProto_Builder*) setOptions:(FieldOptions*) value;
- (FieldDescriptorProto_Builder*) setOptionsBuilder:(FieldOptions_Builder*) builderForValue;
- (FieldDescriptorProto_Builder*) mergeOptions:(FieldOptions*) value;
- (FieldDescriptorProto_Builder*) clearOptions;
@end

@interface EnumDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  EnumOptions* options;
  NSMutableArray* mutableValueList;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) EnumOptions* options;
- (NSArray*) valueList;
- (EnumValueDescriptorProto*) valueAtIndex:(int32_t) index;

+ (EnumDescriptorProto*) defaultInstance;
- (EnumDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnumDescriptorProto_Builder*) builder;
+ (EnumDescriptorProto_Builder*) builder;
+ (EnumDescriptorProto_Builder*) builderWithPrototype:(EnumDescriptorProto*) prototype;

+ (EnumDescriptorProto*) parseFromData:(NSData*) data;
+ (EnumDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (EnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnumDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnumDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  EnumDescriptorProto* result;
}

- (EnumDescriptorProto*) defaultInstance;

- (EnumDescriptorProto_Builder*) clear;
- (EnumDescriptorProto_Builder*) clone;

- (EnumDescriptorProto*) build;
- (EnumDescriptorProto*) buildPartial;

- (EnumDescriptorProto_Builder*) mergeFrom:(EnumDescriptorProto*) other;
- (EnumDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnumDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (EnumDescriptorProto_Builder*) setName:(NSString*) value;
- (EnumDescriptorProto_Builder*) clearName;

- (NSArray*) valueList;
- (EnumValueDescriptorProto*) valueAtIndex:(int32_t) index;
- (EnumDescriptorProto_Builder*) replaceValueAtIndex:(int32_t) index with:(EnumValueDescriptorProto*) value;
- (EnumDescriptorProto_Builder*) addValue:(EnumValueDescriptorProto*) value;
- (EnumDescriptorProto_Builder*) addAllValue:(NSArray*) values;
- (EnumDescriptorProto_Builder*) clearValueList;

- (BOOL) hasOptions;
- (EnumOptions*) options;
- (EnumDescriptorProto_Builder*) setOptions:(EnumOptions*) value;
- (EnumDescriptorProto_Builder*) setOptionsBuilder:(EnumOptions_Builder*) builderForValue;
- (EnumDescriptorProto_Builder*) mergeOptions:(EnumOptions*) value;
- (EnumDescriptorProto_Builder*) clearOptions;
@end

@interface EnumValueDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  int32_t number;
  NSString* name;
  EnumValueOptions* options;
}
- (BOOL) hasName;
- (BOOL) hasNumber;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t number;
@property (readonly, retain) EnumValueOptions* options;

+ (EnumValueDescriptorProto*) defaultInstance;
- (EnumValueDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnumValueDescriptorProto_Builder*) builder;
+ (EnumValueDescriptorProto_Builder*) builder;
+ (EnumValueDescriptorProto_Builder*) builderWithPrototype:(EnumValueDescriptorProto*) prototype;

+ (EnumValueDescriptorProto*) parseFromData:(NSData*) data;
+ (EnumValueDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (EnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumValueDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnumValueDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnumValueDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  EnumValueDescriptorProto* result;
}

- (EnumValueDescriptorProto*) defaultInstance;

- (EnumValueDescriptorProto_Builder*) clear;
- (EnumValueDescriptorProto_Builder*) clone;

- (EnumValueDescriptorProto*) build;
- (EnumValueDescriptorProto*) buildPartial;

- (EnumValueDescriptorProto_Builder*) mergeFrom:(EnumValueDescriptorProto*) other;
- (EnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (EnumValueDescriptorProto_Builder*) setName:(NSString*) value;
- (EnumValueDescriptorProto_Builder*) clearName;

- (BOOL) hasNumber;
- (int32_t) number;
- (EnumValueDescriptorProto_Builder*) setNumber:(int32_t) value;
- (EnumValueDescriptorProto_Builder*) clearNumber;

- (BOOL) hasOptions;
- (EnumValueOptions*) options;
- (EnumValueDescriptorProto_Builder*) setOptions:(EnumValueOptions*) value;
- (EnumValueDescriptorProto_Builder*) setOptionsBuilder:(EnumValueOptions_Builder*) builderForValue;
- (EnumValueDescriptorProto_Builder*) mergeOptions:(EnumValueOptions*) value;
- (EnumValueDescriptorProto_Builder*) clearOptions;
@end

@interface ServiceDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  ServiceOptions* options;
  NSMutableArray* mutableMethodList;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) ServiceOptions* options;
- (NSArray*) methodList;
- (MethodDescriptorProto*) methodAtIndex:(int32_t) index;

+ (ServiceDescriptorProto*) defaultInstance;
- (ServiceDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServiceDescriptorProto_Builder*) builder;
+ (ServiceDescriptorProto_Builder*) builder;
+ (ServiceDescriptorProto_Builder*) builderWithPrototype:(ServiceDescriptorProto*) prototype;

+ (ServiceDescriptorProto*) parseFromData:(NSData*) data;
+ (ServiceDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (ServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServiceDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServiceDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServiceDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  ServiceDescriptorProto* result;
}

- (ServiceDescriptorProto*) defaultInstance;

- (ServiceDescriptorProto_Builder*) clear;
- (ServiceDescriptorProto_Builder*) clone;

- (ServiceDescriptorProto*) build;
- (ServiceDescriptorProto*) buildPartial;

- (ServiceDescriptorProto_Builder*) mergeFrom:(ServiceDescriptorProto*) other;
- (ServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (ServiceDescriptorProto_Builder*) setName:(NSString*) value;
- (ServiceDescriptorProto_Builder*) clearName;

- (NSArray*) methodList;
- (MethodDescriptorProto*) methodAtIndex:(int32_t) index;
- (ServiceDescriptorProto_Builder*) replaceMethodAtIndex:(int32_t) index with:(MethodDescriptorProto*) value;
- (ServiceDescriptorProto_Builder*) addMethod:(MethodDescriptorProto*) value;
- (ServiceDescriptorProto_Builder*) addAllMethod:(NSArray*) values;
- (ServiceDescriptorProto_Builder*) clearMethodList;

- (BOOL) hasOptions;
- (ServiceOptions*) options;
- (ServiceDescriptorProto_Builder*) setOptions:(ServiceOptions*) value;
- (ServiceDescriptorProto_Builder*) setOptionsBuilder:(ServiceOptions_Builder*) builderForValue;
- (ServiceDescriptorProto_Builder*) mergeOptions:(ServiceOptions*) value;
- (ServiceDescriptorProto_Builder*) clearOptions;
@end

@interface MethodDescriptorProto : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasInputType_:1;
  BOOL hasOutputType_:1;
  BOOL hasOptions_:1;
  NSString* name;
  NSString* inputType;
  NSString* outputType;
  MethodOptions* options;
}
- (BOOL) hasName;
- (BOOL) hasInputType;
- (BOOL) hasOutputType;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* inputType;
@property (readonly, retain) NSString* outputType;
@property (readonly, retain) MethodOptions* options;

+ (MethodDescriptorProto*) defaultInstance;
- (MethodDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MethodDescriptorProto_Builder*) builder;
+ (MethodDescriptorProto_Builder*) builder;
+ (MethodDescriptorProto_Builder*) builderWithPrototype:(MethodDescriptorProto*) prototype;

+ (MethodDescriptorProto*) parseFromData:(NSData*) data;
+ (MethodDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (MethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MethodDescriptorProto*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MethodDescriptorProto_Builder : PBGeneratedMessage_Builder {
@private
  MethodDescriptorProto* result;
}

- (MethodDescriptorProto*) defaultInstance;

- (MethodDescriptorProto_Builder*) clear;
- (MethodDescriptorProto_Builder*) clone;

- (MethodDescriptorProto*) build;
- (MethodDescriptorProto*) buildPartial;

- (MethodDescriptorProto_Builder*) mergeFrom:(MethodDescriptorProto*) other;
- (MethodDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MethodDescriptorProto_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (MethodDescriptorProto_Builder*) setName:(NSString*) value;
- (MethodDescriptorProto_Builder*) clearName;

- (BOOL) hasInputType;
- (NSString*) inputType;
- (MethodDescriptorProto_Builder*) setInputType:(NSString*) value;
- (MethodDescriptorProto_Builder*) clearInputType;

- (BOOL) hasOutputType;
- (NSString*) outputType;
- (MethodDescriptorProto_Builder*) setOutputType:(NSString*) value;
- (MethodDescriptorProto_Builder*) clearOutputType;

- (BOOL) hasOptions;
- (MethodOptions*) options;
- (MethodDescriptorProto_Builder*) setOptions:(MethodOptions*) value;
- (MethodDescriptorProto_Builder*) setOptionsBuilder:(MethodOptions_Builder*) builderForValue;
- (MethodDescriptorProto_Builder*) mergeOptions:(MethodOptions*) value;
- (MethodDescriptorProto_Builder*) clearOptions;
@end

@interface FileOptions : PBExtendableMessage {
@private
  BOOL hasJavaMultipleFiles_:1;
  BOOL hasJavaPackage_:1;
  BOOL hasJavaOuterClassname_:1;
  BOOL hasOptimizeFor_:1;
  BOOL javaMultipleFiles_:1;
  NSString* javaPackage;
  NSString* javaOuterClassname;
  FileOptions_OptimizeMode optimizeFor;
  NSMutableArray* mutableUninterpretedOptionList;
}
- (BOOL) hasJavaPackage;
- (BOOL) hasJavaOuterClassname;
- (BOOL) hasJavaMultipleFiles;
- (BOOL) hasOptimizeFor;
@property (readonly, retain) NSString* javaPackage;
@property (readonly, retain) NSString* javaOuterClassname;
- (BOOL) javaMultipleFiles;
@property (readonly) FileOptions_OptimizeMode optimizeFor;
- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (FileOptions*) defaultInstance;
- (FileOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FileOptions_Builder*) builder;
+ (FileOptions_Builder*) builder;
+ (FileOptions_Builder*) builderWithPrototype:(FileOptions*) prototype;

+ (FileOptions*) parseFromData:(NSData*) data;
+ (FileOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileOptions*) parseFromInputStream:(NSInputStream*) input;
+ (FileOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FileOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FileOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FileOptions_Builder : PBExtendableMessage_Builder {
@private
  FileOptions* result;
}

- (FileOptions*) defaultInstance;

- (FileOptions_Builder*) clear;
- (FileOptions_Builder*) clone;

- (FileOptions*) build;
- (FileOptions*) buildPartial;

- (FileOptions_Builder*) mergeFrom:(FileOptions*) other;
- (FileOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FileOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasJavaPackage;
- (NSString*) javaPackage;
- (FileOptions_Builder*) setJavaPackage:(NSString*) value;
- (FileOptions_Builder*) clearJavaPackage;

- (BOOL) hasJavaOuterClassname;
- (NSString*) javaOuterClassname;
- (FileOptions_Builder*) setJavaOuterClassname:(NSString*) value;
- (FileOptions_Builder*) clearJavaOuterClassname;

- (BOOL) hasJavaMultipleFiles;
- (BOOL) javaMultipleFiles;
- (FileOptions_Builder*) setJavaMultipleFiles:(BOOL) value;
- (FileOptions_Builder*) clearJavaMultipleFiles;

- (BOOL) hasOptimizeFor;
- (FileOptions_OptimizeMode) optimizeFor;
- (FileOptions_Builder*) setOptimizeFor:(FileOptions_OptimizeMode) value;
- (FileOptions_Builder*) clearOptimizeFor;

- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (FileOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(UninterpretedOption*) value;
- (FileOptions_Builder*) addUninterpretedOption:(UninterpretedOption*) value;
- (FileOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (FileOptions_Builder*) clearUninterpretedOptionList;
@end

@interface MessageOptions : PBExtendableMessage {
@private
  BOOL hasMessageSetWireFormat_:1;
  BOOL hasNoStandardDescriptorAccessor_:1;
  BOOL messageSetWireFormat_:1;
  BOOL noStandardDescriptorAccessor_:1;
  NSMutableArray* mutableUninterpretedOptionList;
}
- (BOOL) hasMessageSetWireFormat;
- (BOOL) hasNoStandardDescriptorAccessor;
- (BOOL) messageSetWireFormat;
- (BOOL) noStandardDescriptorAccessor;
- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (MessageOptions*) defaultInstance;
- (MessageOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MessageOptions_Builder*) builder;
+ (MessageOptions_Builder*) builder;
+ (MessageOptions_Builder*) builderWithPrototype:(MessageOptions*) prototype;

+ (MessageOptions*) parseFromData:(NSData*) data;
+ (MessageOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageOptions*) parseFromInputStream:(NSInputStream*) input;
+ (MessageOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MessageOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MessageOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MessageOptions_Builder : PBExtendableMessage_Builder {
@private
  MessageOptions* result;
}

- (MessageOptions*) defaultInstance;

- (MessageOptions_Builder*) clear;
- (MessageOptions_Builder*) clone;

- (MessageOptions*) build;
- (MessageOptions*) buildPartial;

- (MessageOptions_Builder*) mergeFrom:(MessageOptions*) other;
- (MessageOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MessageOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageSetWireFormat;
- (BOOL) messageSetWireFormat;
- (MessageOptions_Builder*) setMessageSetWireFormat:(BOOL) value;
- (MessageOptions_Builder*) clearMessageSetWireFormat;

- (BOOL) hasNoStandardDescriptorAccessor;
- (BOOL) noStandardDescriptorAccessor;
- (MessageOptions_Builder*) setNoStandardDescriptorAccessor:(BOOL) value;
- (MessageOptions_Builder*) clearNoStandardDescriptorAccessor;

- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (MessageOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(UninterpretedOption*) value;
- (MessageOptions_Builder*) addUninterpretedOption:(UninterpretedOption*) value;
- (MessageOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (MessageOptions_Builder*) clearUninterpretedOptionList;
@end

@interface FieldOptions : PBExtendableMessage {
@private
  BOOL hasPacked_:1;
  BOOL hasDeprecated_:1;
  BOOL hasExperimentalMapKey_:1;
  BOOL hasCtype_:1;
  BOOL packed_:1;
  BOOL deprecated_:1;
  NSString* experimentalMapKey;
  FieldOptions_CType ctype;
  NSMutableArray* mutableUninterpretedOptionList;
}
- (BOOL) hasCtype;
- (BOOL) hasPacked;
- (BOOL) hasDeprecated;
- (BOOL) hasExperimentalMapKey;
@property (readonly) FieldOptions_CType ctype;
- (BOOL) packed;
- (BOOL) deprecated;
@property (readonly, retain) NSString* experimentalMapKey;
- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (FieldOptions*) defaultInstance;
- (FieldOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FieldOptions_Builder*) builder;
+ (FieldOptions_Builder*) builder;
+ (FieldOptions_Builder*) builderWithPrototype:(FieldOptions*) prototype;

+ (FieldOptions*) parseFromData:(NSData*) data;
+ (FieldOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FieldOptions*) parseFromInputStream:(NSInputStream*) input;
+ (FieldOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FieldOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FieldOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FieldOptions_Builder : PBExtendableMessage_Builder {
@private
  FieldOptions* result;
}

- (FieldOptions*) defaultInstance;

- (FieldOptions_Builder*) clear;
- (FieldOptions_Builder*) clone;

- (FieldOptions*) build;
- (FieldOptions*) buildPartial;

- (FieldOptions_Builder*) mergeFrom:(FieldOptions*) other;
- (FieldOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FieldOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCtype;
- (FieldOptions_CType) ctype;
- (FieldOptions_Builder*) setCtype:(FieldOptions_CType) value;
- (FieldOptions_Builder*) clearCtype;

- (BOOL) hasPacked;
- (BOOL) packed;
- (FieldOptions_Builder*) setPacked:(BOOL) value;
- (FieldOptions_Builder*) clearPacked;

- (BOOL) hasDeprecated;
- (BOOL) deprecated;
- (FieldOptions_Builder*) setDeprecated:(BOOL) value;
- (FieldOptions_Builder*) clearDeprecated;

- (BOOL) hasExperimentalMapKey;
- (NSString*) experimentalMapKey;
- (FieldOptions_Builder*) setExperimentalMapKey:(NSString*) value;
- (FieldOptions_Builder*) clearExperimentalMapKey;

- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (FieldOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(UninterpretedOption*) value;
- (FieldOptions_Builder*) addUninterpretedOption:(UninterpretedOption*) value;
- (FieldOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (FieldOptions_Builder*) clearUninterpretedOptionList;
@end

@interface EnumOptions : PBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (EnumOptions*) defaultInstance;
- (EnumOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnumOptions_Builder*) builder;
+ (EnumOptions_Builder*) builder;
+ (EnumOptions_Builder*) builderWithPrototype:(EnumOptions*) prototype;

+ (EnumOptions*) parseFromData:(NSData*) data;
+ (EnumOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumOptions*) parseFromInputStream:(NSInputStream*) input;
+ (EnumOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnumOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnumOptions_Builder : PBExtendableMessage_Builder {
@private
  EnumOptions* result;
}

- (EnumOptions*) defaultInstance;

- (EnumOptions_Builder*) clear;
- (EnumOptions_Builder*) clone;

- (EnumOptions*) build;
- (EnumOptions*) buildPartial;

- (EnumOptions_Builder*) mergeFrom:(EnumOptions*) other;
- (EnumOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnumOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (EnumOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(UninterpretedOption*) value;
- (EnumOptions_Builder*) addUninterpretedOption:(UninterpretedOption*) value;
- (EnumOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (EnumOptions_Builder*) clearUninterpretedOptionList;
@end

@interface EnumValueOptions : PBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (EnumValueOptions*) defaultInstance;
- (EnumValueOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EnumValueOptions_Builder*) builder;
+ (EnumValueOptions_Builder*) builder;
+ (EnumValueOptions_Builder*) builderWithPrototype:(EnumValueOptions*) prototype;

+ (EnumValueOptions*) parseFromData:(NSData*) data;
+ (EnumValueOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumValueOptions*) parseFromInputStream:(NSInputStream*) input;
+ (EnumValueOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EnumValueOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EnumValueOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EnumValueOptions_Builder : PBExtendableMessage_Builder {
@private
  EnumValueOptions* result;
}

- (EnumValueOptions*) defaultInstance;

- (EnumValueOptions_Builder*) clear;
- (EnumValueOptions_Builder*) clone;

- (EnumValueOptions*) build;
- (EnumValueOptions*) buildPartial;

- (EnumValueOptions_Builder*) mergeFrom:(EnumValueOptions*) other;
- (EnumValueOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EnumValueOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (EnumValueOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(UninterpretedOption*) value;
- (EnumValueOptions_Builder*) addUninterpretedOption:(UninterpretedOption*) value;
- (EnumValueOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (EnumValueOptions_Builder*) clearUninterpretedOptionList;
@end

@interface ServiceOptions : PBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (ServiceOptions*) defaultInstance;
- (ServiceOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServiceOptions_Builder*) builder;
+ (ServiceOptions_Builder*) builder;
+ (ServiceOptions_Builder*) builderWithPrototype:(ServiceOptions*) prototype;

+ (ServiceOptions*) parseFromData:(NSData*) data;
+ (ServiceOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServiceOptions*) parseFromInputStream:(NSInputStream*) input;
+ (ServiceOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ServiceOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ServiceOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServiceOptions_Builder : PBExtendableMessage_Builder {
@private
  ServiceOptions* result;
}

- (ServiceOptions*) defaultInstance;

- (ServiceOptions_Builder*) clear;
- (ServiceOptions_Builder*) clone;

- (ServiceOptions*) build;
- (ServiceOptions*) buildPartial;

- (ServiceOptions_Builder*) mergeFrom:(ServiceOptions*) other;
- (ServiceOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServiceOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (ServiceOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(UninterpretedOption*) value;
- (ServiceOptions_Builder*) addUninterpretedOption:(UninterpretedOption*) value;
- (ServiceOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (ServiceOptions_Builder*) clearUninterpretedOptionList;
@end

@interface MethodOptions : PBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (MethodOptions*) defaultInstance;
- (MethodOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MethodOptions_Builder*) builder;
+ (MethodOptions_Builder*) builder;
+ (MethodOptions_Builder*) builderWithPrototype:(MethodOptions*) prototype;

+ (MethodOptions*) parseFromData:(NSData*) data;
+ (MethodOptions*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodOptions*) parseFromInputStream:(NSInputStream*) input;
+ (MethodOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MethodOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MethodOptions*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MethodOptions_Builder : PBExtendableMessage_Builder {
@private
  MethodOptions* result;
}

- (MethodOptions*) defaultInstance;

- (MethodOptions_Builder*) clear;
- (MethodOptions_Builder*) clone;

- (MethodOptions*) build;
- (MethodOptions*) buildPartial;

- (MethodOptions_Builder*) mergeFrom:(MethodOptions*) other;
- (MethodOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MethodOptions_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (UninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (MethodOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(UninterpretedOption*) value;
- (MethodOptions_Builder*) addUninterpretedOption:(UninterpretedOption*) value;
- (MethodOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (MethodOptions_Builder*) clearUninterpretedOptionList;
@end

@interface UninterpretedOption : PBGeneratedMessage {
@private
  BOOL hasDoubleValue_:1;
  BOOL hasNegativeIntValue_:1;
  BOOL hasPositiveIntValue_:1;
  BOOL hasIdentifierValue_:1;
  BOOL hasStringValue_:1;
  Float64 doubleValue;
  int64_t negativeIntValue;
  int64_t positiveIntValue;
  NSString* identifierValue;
  NSData* stringValue;
  NSMutableArray* mutableNameList;
}
- (BOOL) hasIdentifierValue;
- (BOOL) hasPositiveIntValue;
- (BOOL) hasNegativeIntValue;
- (BOOL) hasDoubleValue;
- (BOOL) hasStringValue;
@property (readonly, retain) NSString* identifierValue;
@property (readonly) int64_t positiveIntValue;
@property (readonly) int64_t negativeIntValue;
@property (readonly) Float64 doubleValue;
@property (readonly, retain) NSData* stringValue;
- (NSArray*) nameList;
- (UninterpretedOption_NamePart*) nameAtIndex:(int32_t) index;

+ (UninterpretedOption*) defaultInstance;
- (UninterpretedOption*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UninterpretedOption_Builder*) builder;
+ (UninterpretedOption_Builder*) builder;
+ (UninterpretedOption_Builder*) builderWithPrototype:(UninterpretedOption*) prototype;

+ (UninterpretedOption*) parseFromData:(NSData*) data;
+ (UninterpretedOption*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UninterpretedOption*) parseFromInputStream:(NSInputStream*) input;
+ (UninterpretedOption*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UninterpretedOption*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UninterpretedOption*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UninterpretedOption_NamePart : PBGeneratedMessage {
@private
  BOOL hasIsExtension_:1;
  BOOL hasNamePart_:1;
  BOOL isExtension_:1;
  NSString* namePart;
}
- (BOOL) hasNamePart;
- (BOOL) hasIsExtension;
@property (readonly, retain) NSString* namePart;
- (BOOL) isExtension;

+ (UninterpretedOption_NamePart*) defaultInstance;
- (UninterpretedOption_NamePart*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UninterpretedOption_NamePart_Builder*) builder;
+ (UninterpretedOption_NamePart_Builder*) builder;
+ (UninterpretedOption_NamePart_Builder*) builderWithPrototype:(UninterpretedOption_NamePart*) prototype;

+ (UninterpretedOption_NamePart*) parseFromData:(NSData*) data;
+ (UninterpretedOption_NamePart*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UninterpretedOption_NamePart*) parseFromInputStream:(NSInputStream*) input;
+ (UninterpretedOption_NamePart*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UninterpretedOption_NamePart*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UninterpretedOption_NamePart*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UninterpretedOption_NamePart_Builder : PBGeneratedMessage_Builder {
@private
  UninterpretedOption_NamePart* result;
}

- (UninterpretedOption_NamePart*) defaultInstance;

- (UninterpretedOption_NamePart_Builder*) clear;
- (UninterpretedOption_NamePart_Builder*) clone;

- (UninterpretedOption_NamePart*) build;
- (UninterpretedOption_NamePart*) buildPartial;

- (UninterpretedOption_NamePart_Builder*) mergeFrom:(UninterpretedOption_NamePart*) other;
- (UninterpretedOption_NamePart_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UninterpretedOption_NamePart_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNamePart;
- (NSString*) namePart;
- (UninterpretedOption_NamePart_Builder*) setNamePart:(NSString*) value;
- (UninterpretedOption_NamePart_Builder*) clearNamePart;

- (BOOL) hasIsExtension;
- (BOOL) isExtension;
- (UninterpretedOption_NamePart_Builder*) setIsExtension:(BOOL) value;
- (UninterpretedOption_NamePart_Builder*) clearIsExtension;
@end

@interface UninterpretedOption_Builder : PBGeneratedMessage_Builder {
@private
  UninterpretedOption* result;
}

- (UninterpretedOption*) defaultInstance;

- (UninterpretedOption_Builder*) clear;
- (UninterpretedOption_Builder*) clone;

- (UninterpretedOption*) build;
- (UninterpretedOption*) buildPartial;

- (UninterpretedOption_Builder*) mergeFrom:(UninterpretedOption*) other;
- (UninterpretedOption_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UninterpretedOption_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) nameList;
- (UninterpretedOption_NamePart*) nameAtIndex:(int32_t) index;
- (UninterpretedOption_Builder*) replaceNameAtIndex:(int32_t) index with:(UninterpretedOption_NamePart*) value;
- (UninterpretedOption_Builder*) addName:(UninterpretedOption_NamePart*) value;
- (UninterpretedOption_Builder*) addAllName:(NSArray*) values;
- (UninterpretedOption_Builder*) clearNameList;

- (BOOL) hasIdentifierValue;
- (NSString*) identifierValue;
- (UninterpretedOption_Builder*) setIdentifierValue:(NSString*) value;
- (UninterpretedOption_Builder*) clearIdentifierValue;

- (BOOL) hasPositiveIntValue;
- (int64_t) positiveIntValue;
- (UninterpretedOption_Builder*) setPositiveIntValue:(int64_t) value;
- (UninterpretedOption_Builder*) clearPositiveIntValue;

- (BOOL) hasNegativeIntValue;
- (int64_t) negativeIntValue;
- (UninterpretedOption_Builder*) setNegativeIntValue:(int64_t) value;
- (UninterpretedOption_Builder*) clearNegativeIntValue;

- (BOOL) hasDoubleValue;
- (Float64) doubleValue;
- (UninterpretedOption_Builder*) setDoubleValue:(Float64) value;
- (UninterpretedOption_Builder*) clearDoubleValue;

- (BOOL) hasStringValue;
- (NSData*) stringValue;
- (UninterpretedOption_Builder*) setStringValue:(NSData*) value;
- (UninterpretedOption_Builder*) clearStringValue;
@end

