// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class FederationError;
@class FederationError_Builder;
typedef enum {
  FederationError_CodeOk = 0,
  FederationError_CodeBadRequest = 1,
  FederationError_CodeItemNotFound = 2,
  FederationError_CodeNotAcceptable = 3,
  FederationError_CodeNotAuthorized = 4,
  FederationError_CodeResourceConstraint = 5,
  FederationError_CodeUndefinedCondition = 6,
  FederationError_CodeRemoteServerTimeout = 7,
  FederationError_CodeUnexpectedRequest = 8,
} FederationError_Code;

BOOL FederationError_CodeIsValidValue(FederationError_Code value);


@interface FederationErrorRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface FederationError : PBGeneratedMessage {
@private
  BOOL hasErrorMessage_:1;
  BOOL hasErrorCode_:1;
  NSString* errorMessage;
  FederationError_Code errorCode;
}
- (BOOL) hasErrorCode;
- (BOOL) hasErrorMessage;
@property (readonly) FederationError_Code errorCode;
@property (readonly, retain) NSString* errorMessage;

+ (FederationError*) defaultInstance;
- (FederationError*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FederationError_Builder*) builder;
+ (FederationError_Builder*) builder;
+ (FederationError_Builder*) builderWithPrototype:(FederationError*) prototype;

+ (FederationError*) parseFromData:(NSData*) data;
+ (FederationError*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FederationError*) parseFromInputStream:(NSInputStream*) input;
+ (FederationError*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FederationError*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FederationError*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FederationError_Builder : PBGeneratedMessage_Builder {
@private
  FederationError* result;
}

- (FederationError*) defaultInstance;

- (FederationError_Builder*) clear;
- (FederationError_Builder*) clone;

- (FederationError*) build;
- (FederationError*) buildPartial;

- (FederationError_Builder*) mergeFrom:(FederationError*) other;
- (FederationError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FederationError_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasErrorCode;
- (FederationError_Code) errorCode;
- (FederationError_Builder*) setErrorCode:(FederationError_Code) value;
- (FederationError_Builder*) clearErrorCode;

- (BOOL) hasErrorMessage;
- (NSString*) errorMessage;
- (FederationError_Builder*) setErrorMessage:(NSString*) value;
- (FederationError_Builder*) clearErrorMessage;
@end

