// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "Descriptor.pb.h"
#import "ObjectivecDescriptor.pb.h"

@class CancelRpc;
@class CancelRpc_Builder;
@class DescriptorProto;
@class DescriptorProto_Builder;
@class DescriptorProto_ExtensionRange;
@class DescriptorProto_ExtensionRange_Builder;
@class EnumDescriptorProto;
@class EnumDescriptorProto_Builder;
@class EnumOptions;
@class EnumOptions_Builder;
@class EnumValueDescriptorProto;
@class EnumValueDescriptorProto_Builder;
@class EnumValueOptions;
@class EnumValueOptions_Builder;
@class FieldDescriptorProto;
@class FieldDescriptorProto_Builder;
@class FieldOptions;
@class FieldOptions_Builder;
@class FileDescriptorProto;
@class FileDescriptorProto_Builder;
@class FileDescriptorSet;
@class FileDescriptorSet_Builder;
@class FileOptions;
@class FileOptions_Builder;
@class MessageOptions;
@class MessageOptions_Builder;
@class MethodDescriptorProto;
@class MethodDescriptorProto_Builder;
@class MethodOptions;
@class MethodOptions_Builder;
@class ObjectiveCFileOptions;
@class ObjectiveCFileOptions_Builder;
@class RpcFinished;
@class RpcFinished_Builder;
@class ServiceDescriptorProto;
@class ServiceDescriptorProto_Builder;
@class ServiceOptions;
@class ServiceOptions_Builder;
@class UninterpretedOption;
@class UninterpretedOption_Builder;
@class UninterpretedOption_NamePart;
@class UninterpretedOption_NamePart_Builder;

@interface RpcRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) isStreamingRpc;
@end

@interface CancelRpc : PBGeneratedMessage {
@private
}

+ (CancelRpc*) defaultInstance;
- (CancelRpc*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CancelRpc_Builder*) builder;
+ (CancelRpc_Builder*) builder;
+ (CancelRpc_Builder*) builderWithPrototype:(CancelRpc*) prototype;

+ (CancelRpc*) parseFromData:(NSData*) data;
+ (CancelRpc*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CancelRpc*) parseFromInputStream:(NSInputStream*) input;
+ (CancelRpc*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CancelRpc*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CancelRpc*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CancelRpc_Builder : PBGeneratedMessage_Builder {
@private
  CancelRpc* result;
}

- (CancelRpc*) defaultInstance;

- (CancelRpc_Builder*) clear;
- (CancelRpc_Builder*) clone;

- (CancelRpc*) build;
- (CancelRpc*) buildPartial;

- (CancelRpc_Builder*) mergeFrom:(CancelRpc*) other;
- (CancelRpc_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CancelRpc_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RpcFinished : PBGeneratedMessage {
@private
  BOOL hasFailed_:1;
  BOOL hasErrorText_:1;
  BOOL failed_:1;
  NSString* errorText;
}
- (BOOL) hasFailed;
- (BOOL) hasErrorText;
- (BOOL) failed;
@property (readonly, retain) NSString* errorText;

+ (RpcFinished*) defaultInstance;
- (RpcFinished*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RpcFinished_Builder*) builder;
+ (RpcFinished_Builder*) builder;
+ (RpcFinished_Builder*) builderWithPrototype:(RpcFinished*) prototype;

+ (RpcFinished*) parseFromData:(NSData*) data;
+ (RpcFinished*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RpcFinished*) parseFromInputStream:(NSInputStream*) input;
+ (RpcFinished*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RpcFinished*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RpcFinished*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RpcFinished_Builder : PBGeneratedMessage_Builder {
@private
  RpcFinished* result;
}

- (RpcFinished*) defaultInstance;

- (RpcFinished_Builder*) clear;
- (RpcFinished_Builder*) clone;

- (RpcFinished*) build;
- (RpcFinished*) buildPartial;

- (RpcFinished_Builder*) mergeFrom:(RpcFinished*) other;
- (RpcFinished_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RpcFinished_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFailed;
- (BOOL) failed;
- (RpcFinished_Builder*) setFailed:(BOOL) value;
- (RpcFinished_Builder*) clearFailed;

- (BOOL) hasErrorText;
- (NSString*) errorText;
- (RpcFinished_Builder*) setErrorText:(NSString*) value;
- (RpcFinished_Builder*) clearErrorText;
@end

